config/routes.rb
Rails.application.routes.draw do
resources :topics, except: [:index]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'vue-items', to: 'portfolios#vue'
  get 'ruby-on-rails-items', to: 'portfolios#ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggel_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates :title, presence: true
    has_many :blogs
    def self.own_blogs
        includes(:blogs).where.not(blogs: {id: nil})
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy, :toggel_status]
  layout "blog"
  access all: [:show], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def show
    if logged_in? :site_admin
      @blogs = @topic.blogs.recent.paginate(page: params[:page], per_page: 5)
    else
      @blogs = @topic.blogs.published.recent.paginate(page: params[:page], per_page: 5)
    end
  end

  def new
    @topic = Topic.new
  end

  def edit
  end
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, notice: @topic.errors }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_topic
      @topic = Topic.find(params[:id])
    end
    def topic_params
      params.require(:topic).permit(:title)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |form| %>
    <% if @topic.errors.any? %>
      <% @topic.errors.full_messages.each do |error| %>
        <%= alert_generator error %>
      <% end %>
    <% end %>
  
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, id: :topic_title, class: "form-control", placeholder: 'Title' %>
    </div>
  
    <div class="form-group">
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
  

app/views/topics/_topic.html.erb
<li><%= link_to topic.title, topic_path(topic) %></li>

app/views/topics/edit.html.erb
<div class="col-md-8 blog-main">
    <h1>Editing Topic</h1>

    <%= render 'form', topic: @topic %>

    <%= link_to 'Show', @topic %> |
    <%= link_to 'Back', topics_path %>
</div>

app/views/topics/new.html.erb
<div class="col-md-8 blog-main">
    <h1>New Topic</h1>

    <%= render 'form', topic: @topic %>

    <%= link_to 'Back', topics_path %>
</div>

app/views/topics/show.html.erb
<div class="col-md-8 blog-main">
    <%= will_paginate @blogs, renderer: BootstrapPagination::Rails %>
    <h3 class="pb-4 mb-4 font-italic border-bottom">
        <%= @topic.title %> /
        <%= link_to 'Edit', edit_topic_path(@topic) if logged_in?(:site_admin) %>
    </h3>

    <%= render @blogs %>
    <%= will_paginate @blogs, renderer: BootstrapPagination::Rails %>
</div>