config/routes.rb
Rails.application.routes.draw do
resources :topics, except: [:index]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'vue-items', to: 'portfolios#vue'
  get 'ruby-on-rails-items', to: 'portfolios#ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggel_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies, 
                                    allow_destroy: true,
                                    reject_if: lambda { |attrs| attrs['name'].blank? }
    validates_presence_of :title, :body
    mount_uploader :thub_image, PortfolioUploader
    mount_uploader :main_image, PortfolioUploader
    def self.vue
        where(subtitle: 'vue js')
    end
    def self.by_position
        order("position ASC")
    end
    scope :ruby_on_rails, -> { where(subtitle: 'Ruby On Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :set_portfolio_item, only: [:edit, :update, :show, :destory]
    layout "portfolio"
    access all: [:show, :index, :ruby_on_rails, :vue], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

    def index
        @portfolio_items= Portfolio.by_position
    end
    def sort
        params[:order].each do |key, value|
            Portfolio.find(value[:id]).update(position: value[:position])
        end
        render nothing: true
    end
    def vue
        @vue_portfolio_items= Portfolio.vue 
    end
    def ruby_on_rails
        @ruby_on_rails_portfolio_items= Portfolio.ruby_on_rails
    end
    def new
        @portfolio_item = Portfolio.new
    end
    def create
        @portfolio_item = Portfolio.new(portfolio_param)

        respond_to do |format|
            if @portfolio_item.save
                format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end
    def edit 
    end
    def update   
        respond_to do |format|
            if @portfolio_item.update(portfolio_param)
              format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
            else
              format.html { render :edit }
            end
          end
    end
    def show       
    end
    def destroy
        @portfolio_item.destroy
        respond_to do |format|
        format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully Deleted.' }
        end
    end
    private
    def portfolio_param
        params.require(:portfolio).permit(:title,
                                          :subtitle, 
                                          :body,
                                          :main_image,
                                          :thub_image,
                                          technologies_attributes: [:id, :name, :_destroy]
                                          )
    end
    def set_portfolio_item
        @portfolio_item= Portfolio.find(params[:id])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

    def image_generator(height:, width:)
        "https://via.placeholder.com/#{height}x#{width}.png?text=Visit+WhoIsHostingThis.com+Buyers+Guide"
    end
    def portfolio_img img, type
        if img.model.main_image? || img.model.thub_image?
            img
        elsif type == 'thumb'
            image_generator(height: '358', width: '250')
        elsif type == 'main'
            image_generator(height: '600', width: '400')
        end
    end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
    <% if @portfolio_item.errors.any? %>
        <% @portfolio_item.errors.full_messages.each do |error| %>
          <%= alert_generator error %>
        <% end %>
      <% end %>
    <div class = "row">
        <div class = "col-md-6">
            <div class="form-group">
                <%= form.label :title %>
                <%= form.text_field :title, id: :portfolio_title, class: 'form-control' %>
            </div>
            
            <div class="form-group">
                <%= form.label :subtitle %>
                <%= form.text_field :subtitle, id: :portfolio_title, class: 'form-control' %>
            </div>
            <div class="form-group">
                <label class='btn btn-primary'>Upload a main image<%= form.file_field :main_image, style: 'display:none;'  %></label>
            </div>
            <div class="form-group">
            <label class='btn btn-primary'>Upload a thumb image<%= form.file_field :thub_image, style: 'display:none;'  %></label>
            </div>
        </div>
        <div class = "col-md-6">
            <div class="form-group">
                <%= form.label :body %>
                <%= form.text_area :body, id: :portfolio_body, class: 'form-control', rows: 13 %>
            </div>
        </div>
    </div>
   
    <hr>
    <div class = "row">
        <div class = "col-md-12">
            <h2>Technologies Used:</h2>
            <div>
                <%= form.fields_for :technologies  do |technology_form|%>
                    <%= render 'technology_fields', f: technology_form %>
                <% end %>
                <div>
                    <%= link_to_add_association 'Add Technology', form, :technologies %>
                </div>
            </div>
            <div class="form-group">
                <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
            </div>
        </div>
    </div>
    <% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
    <div class="card mb-4 shadow-sm" data-id= "<%= portfolio_item.id %> ">
        <%= image_tag portfolio_img portfolio_item.thub_image, 'thumb' %>
        <div class="card-body">
            <p class="card-text">
                <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span>
                <%= portfolio_item.subtitle %>
            </p>
            <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <% if logged_in?(:site_admin) %>
                    <%= link_to "Edit", edit_portfolio_path(portfolio_item), class: 'btn btn-sm btn-outline-secondary' %>
                    <%= link_to 'Delete', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-sm btn-outline-secondary' %>
                <% end %>
            </div>
            <small class="text-muted"><%= distance_of_time_in_words(portfolio_item.created_at, Time.now) %></small>
            </div>
        </div>
    </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class = "container port-padding">
    <h1>Eddit this Portfolio Item</h1>

    <%= render "form", portfolio_item: @portfolio_item %>
    <%= link_to "Back", portfolios_path%>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
    <div class="container">
        <%= source_helper("alert alert-warning") %>
        <div class='row <%= "sortable" if logged_in?(:site_admin) %>'>
            <%= render partial: "portfolio_item", collection: @portfolio_items %>
        </div>
    </div>
</div>

app/views/portfolios/new.html.erb
<div class = "container port-padding">
    <h1> Create new Portfolio Item </h1>
    <%= render "form", portfolio_item: @portfolio_item %>
    <%= link_to "Back", portfolios_path%>
</div>

app/views/portfolios/ruby_on_rails.html.erb
<p id="notice"><%= notice %></p>
<h1>Portfolio Items</h1>

<%= link_to "Create new item", new_portfolio_path if logged_in?(:site_admin) %>

<% @ruby_on_rails_portfolio_items.each do |portfolio_item| %>
<h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>
<p><%= portfolio_item.subtitle %></p>
<p><%= portfolio_item.body %></p>
<%= image_tag portfolio_item.thub_image unless portfolio_item.thub_image.nil? %><br>
<%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
<%= link_to 'Delete', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/show.html.erb
<div class = "container port-padding">
    <div class = "row">
        <div class = "col-md-7">
            <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>
        </div>
        <div class = "col-md-5">
            <h1><%= @portfolio_item.title %></h1>
            <hr>
            <em><%= @portfolio_item.subtitle %></em>
            <p><%= @portfolio_item.body %></p>
            <hr>
            <h3>Technologies Used</h3>
            <% @portfolio_item.technologies.each do |t| %>
                <p><%= t.name %></p>
            <% end %>
        </div>
    </div>
</div>

app/views/portfolios/vue.html.erb
<p id="notice"><%= notice %></p>
<h1>Portfolio Items</h1>

<%= link_to "Create new item", new_portfolio_path if logged_in?(:site_admin) %>

<% @vue_portfolio_items.each do |portfolio_item| %>
<h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>
<p><%= portfolio_item.subtitle %></p>
<p><%= portfolio_item.body %></p>
<%= image_tag portfolio_item.thub_image unless portfolio_item.thub_image.nil? %><br>
<%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
<%= link_to 'Delete', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>