config/routes.rb
Rails.application.routes.draw do
resources :topics, except: [:index]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'vue-items', to: 'portfolios#vue'
  get 'ruby-on-rails-items', to: 'portfolios#ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggel_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
    <div class="inner">
        <p class="app-footer"> <%= copyright_generator %></p>
    </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
    <div class="inner">
        <h3 class="masthead-brand">Omar El Bakali</h3>
        <nav class="nav nav-masthead justify-content-center app-nav">
            <%= nav_helper 'nav-link', 'span' %>
            <%= login_helper 'nav-link' %>
        </nav>
    </div>
</header>

app/views/shared/_archive_topics.html.erb
<li><%= link_to topic.title, topic_path(topic) %></li>

app/views/shared/_blog_featured.html.erb
<% if !Blog.last.nil? %>
  <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
      <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic"><%= Blog.last.title %></h1>
          <p class="lead my-3"><%=  truncate(Blog.last.title, :length => 100) %></p>
          <p class="lead mb-0"><%= link_to "Continue reading..." , Blog.last, class: "text-white font-weight-bold" %></p>
      </div>
  </div>

  <div class="row mb-2">
    <% Blog.feature.each do |blog| %>
      <div class="col-md-6">
          <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
              <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary"><%= blog.topic.title %></strong>
                <h3 class="mb-0">Featured post</h3>
                <div class="mb-1 text-muted">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</div>
                <p class="card-text mb-auto"><%= truncate(blog.body, length: 100) %></p>
                <%= link_to 'Continue reading', blog, class: "stretched-link" %>
              </div>
              <div class="col-auto d-none d-lg-block">
              <%= image_tag image_path('Sunshade.jpg'), class: "bd-placeholder-img", width: "200", height: "250" %>
              </div>
          </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
    <p><%= copyright_generator %></p>
    <p>
    <a href="#">Back to top</a>
    </p>
</footer>

app/views/shared/_blog_header.html.erb
<header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
    <!-- <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
        </div>-->
        <div class="col-4">
            <%= link_to 'Blogs', blogs_path, class: "blog-header-logo text-dark" %>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
        <!-- <a class="text-muted" href="#" aria-label="Search">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
            </a> -->
            <%= login_helper "btn btn-sm btn-outline-secondary" %>
        </div>
    </div>
</header>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between blog-nav">
        <%= nav_helper 'p-2 text-muted', 'span' %>
        <a class="p-2 text-muted" href="#">U.S.</a>
        <a class="p-2 text-muted" href="#">Technology</a>
        <a class="p-2 text-muted" href="#">Design</a>
        <a class="p-2 text-muted" href="#">Business</a>
        <a class="p-2 text-muted" href="#">Politics</a>
        <a class="p-2 text-muted" href="#">Opinion</a>
        <!-- <a class="p-2 text-muted" href="#">Science</a>
        <a class="p-2 text-muted" href="#">Health</a>
        <a class="p-2 text-muted" href="#">Style</a>
        <a class="p-2 text-muted" href="#">Travel</a> -->
    </nav>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
    <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
    </div>
    <%= source_helper("p-4 alert alert-info") %>
    <div class="p-4">
        <h4 class="font-italic">Topics</h4>
        <ol class="list-unstyled mb-0">
            <%  if logged_in? :site_admin %>
                <%= render Topic.all %>
                <hr width="25%" style="margin-left:0px;">
                <%= link_to fa_icon('plus-square') + " New", new_topic_path %>
            <% else%>
                <%= render Topic.own_blogs %>
            <% end %>
          
        </ol>
    </div>

    <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled social-links">
            <li><a href = "https://github.com/bakaliomar" target="_blank"><%= fa_icon "github" %></a></li>
            <li><a href = "https://www.facebook.com/anwar.lalami.5" target="_blank"><%= fa_icon "facebook" %></a></li>
            <li><a href = "https://twitter.com/home" target="_blank"><%= fa_icon "twitter" %></a></li>
            <li><a href = "https://www.instagram.com/omarel.bakali/" target="_blank"><%= fa_icon "instagram" %></a></li>
        </ol>
    </div>
</aside>

app/views/shared/_nav.html.erb
<div class= "<%= location%>">
    <div><%= link_to "Home", root_path %></div>
    <div><%= link_to "Contact-us", contact_path %></div>
    <div><%= link_to "About-us", about_path %></div>
    <div><%= link_to "Blog", blogs_path %></div>
    <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
    <div class="container">
        <p class="float-right pt-4">
            <%= link_to "View All Portfolios", portfolios_path %> /
            <a href="#">Back to top</a>
        </p>
        <p><%= copyright_generator %></p>
    </div>
</footer>

app/views/shared/_portfolio_header.html.erb
<section class="jumbotron text-center">
    <div class="container">
        <h1>My Portfolio</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
            <%= link_to "Find Out More About Me", about_path, class: 'btn btn-primary my-2' %>
            <%= link_to "My Blog", blogs_path, class: 'btn btn-secondary my-2' %>
        </p>
    </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
    <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">About</h4>
            <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Explore</h4>
            <ul class="list-unstyled">
                <%= nav_helper 'text-white', 'li' %>
                <li><%= login_helper 'text-white' %></li>
            </ul>
        </div>
        </div>
    </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
        <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Omar El Bakali</strong>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    </div>
</header>